minFlip: 1000
time: 3
tax: 0.05

#The texture value of the update skull in the menu.
updateValue: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWIzOTE0NTc2YjBiOGU4NzQ5ZTE1ZmJmZWUwNWExNmVhNDEzZDBkNTg1M2M5MDM0MjA5NGViNmFmODI5ZjlmZiJ9fX0="